# Generated by Django 4.1.7 on 2023-04-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("id_history", models.IntegerField(primary_key=True, serialize=False)),
                ("ph", models.FloatField()),
                ("turbidity", models.FloatField()),
                ("tds", models.FloatField()),
                ("result", models.CharField(max_length=50)),
                ("time_posted", models.CharField(max_length=200)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
