# Generated by Django 4.1.7 on 2023-04-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("History", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="id_user",
            new_name="user",
        ),
    ]
